name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet Sentral.API
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Sentral.API/Sentral.API.csproj
        NUGET_KEY: ${{secrets.NUGET}}
        VERSION_FILE_PATH: PackageVersion
        VERSION_REGEX: ^(.*)$
    - name: Publish NuGet Sentral.API.PowerShell
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Sentral.API.PowerShell/Sentral.API.PowerShell.csproj
        NUGET_KEY: ${{secrets.NUGET}}
        VERSION_FILE_PATH: PackageVersion
        VERSION_REGEX: ^(.*)$    
    - name: "Github PreRelease"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
            LICENSE.txt
            *.nupkg
